"""Add push notifications and preferences

Revision ID: 06a30811ae94
Revises: abc123def456
Create Date: 2026-05-03 21:58:12.189207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a30811ae94'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='android | ios | web'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_device_token_user_token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('medicine_reminders', sa.Boolean(), nullable=False),
    sa.Column('chat_messages', sa.Boolean(), nullable=False),
    sa.Column('health_alerts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.alter_column('health_records', 'input_type',
               existing_type=sa.VARCHAR(length=20),
               comment='hospital | urea | medical-report',
               existing_comment='hospital | urea | lcr',
               existing_nullable=False)
    op.alter_column('messages', 'is_read',
               existing_type=sa.VARCHAR(length=5),
               comment='Whether the receiver has opened this message',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique username for users to connect',
               existing_comment='Unique username for doctors — patients use this to connect',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique username for doctors — patients use this to connect',
               existing_comment='Unique username for users to connect',
               existing_nullable=True)
    op.alter_column('messages', 'is_read',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Whether the receiver has opened this message',
               existing_nullable=False)
    op.alter_column('health_records', 'input_type',
               existing_type=sa.VARCHAR(length=20),
               comment='hospital | urea | lcr',
               existing_comment='hospital | urea | medical-report',
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
