"""initial_schema

Revision ID: b5b39edae8de
Revises: 
Create Date: 2026-04-26 11:47:00.854862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b39edae8de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Model name, e.g. 'ckd_risk_hospital', 'ckd_risk_urea'"),
    sa.Column('version', sa.String(length=50), nullable=False, comment="Semantic version, e.g. '1.0.0', '2.1.0-beta'"),
    sa.Column('description', sa.Text(), nullable=True, comment='What this model does, training details, etc.'),
    sa.Column('is_active', sa.String(length=5), nullable=False, comment='Whether this model version is currently active for predictions'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_ml_model_name_version')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False, comment='Primary key — UUID for credentials, Google ID for OAuth'),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Null for Google-only users'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='patient | doctor | empty (not yet chosen)'),
    sa.Column('auth_provider', sa.String(length=20), nullable=False, comment='google | credentials'),
    sa.Column('image', sa.String(length=512), nullable=True, comment='Profile picture URL'),
    sa.Column('doctor_username', sa.String(length=50), nullable=True, comment='Unique username for doctors — patients use this to connect'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_doctor_username'), 'users', ['doctor_username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_created', 'users', ['role', 'created_at'], unique=False)
    op.create_table('doctor_patients',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('doctor_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'patient_id', name='uq_doctor_patient')
    )
    op.create_index('ix_doctor_patients_doctor', 'doctor_patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_doctor_id'), 'doctor_patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_patient_id'), 'doctor_patients', ['patient_id'], unique=False)
    op.create_table('doctor_requests',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('doctor_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | accepted | rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_requests_doctor_id'), 'doctor_requests', ['doctor_id'], unique=False)
    op.create_index('ix_doctor_requests_doctor_status', 'doctor_requests', ['doctor_id', 'status'], unique=False)
    op.create_index(op.f('ix_doctor_requests_patient_id'), 'doctor_requests', ['patient_id'], unique=False)
    op.create_index('ix_doctor_requests_patient_status', 'doctor_requests', ['patient_id', 'status'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False, comment='hospital | urea | lcr'),
    sa.Column('raw_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Flexible JSON storage for any input features — ML-ready'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_created_at'), 'health_records', ['created_at'], unique=False)
    op.create_index('ix_health_records_user_created', 'health_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_index('ix_health_records_user_type', 'health_records', ['user_id', 'input_type'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False, comment='One-time password code'),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=False, comment='When this OTP expires'),
    sa.Column('used', sa.String(length=5), nullable=False, comment='Whether this OTP has been consumed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_resets_user_expiry', 'password_resets', ['user_id', 'expiry_time'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False, comment='One prediction per record'),
    sa.Column('model_id', sa.String(length=255), nullable=True, comment='Which ML model version produced this prediction'),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Prediction result: risk_level, confidence, health_score, explanation, factors'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['health_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_model_created', 'predictions', ['model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_record_id'), 'predictions', ['record_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_record_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index('ix_predictions_model_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index('ix_password_resets_user_expiry', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_health_records_user_type', table_name='health_records')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.drop_index('ix_health_records_user_created', table_name='health_records')
    op.drop_index(op.f('ix_health_records_created_at'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index('ix_doctor_requests_patient_status', table_name='doctor_requests')
    op.drop_index(op.f('ix_doctor_requests_patient_id'), table_name='doctor_requests')
    op.drop_index('ix_doctor_requests_doctor_status', table_name='doctor_requests')
    op.drop_index(op.f('ix_doctor_requests_doctor_id'), table_name='doctor_requests')
    op.drop_table('doctor_requests')
    op.drop_index(op.f('ix_doctor_patients_patient_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_doctor_id'), table_name='doctor_patients')
    op.drop_index('ix_doctor_patients_doctor', table_name='doctor_patients')
    op.drop_table('doctor_patients')
    op.drop_index('ix_users_role_created', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_doctor_username'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
